<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>RASharp</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RASharp.Core\RASharp.Core.csproj" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Update="Meziantou.Analyzer" Version="3.0.156" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RASharp.Tests" />
  </ItemGroup>

</Project>
