<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CHDSharp" Version="1.2.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="VideoGameFileSystemParser" Version="1.2.0" />
    <PackageReference Update="Meziantou.Analyzer" Version="3.0.156" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RASharp.Tests" />
  </ItemGroup>

</Project>
